### ISSUE TITLE
Jellyfish falling from sky

### ISSUE THREAD

**Issue by SettingDust** [hybridlabs/hybrid-aquatic#3]
They are generating on the buildings above ocean

**Comment by amyfromearth** [comment]
Confirming this happens for me as well

**Comment by BelzeWasTaken** [comment]
Same here, makes pillagers raid farm annoying because as you use the elevator, a Jellyfish appears out of nowhere

**Comment by jonko0493** [comment]
They also spawn in tunnels dug out under the ocean. :)

**Comment by Vwriter** [comment]
Yep. Happened for me to.

Not only that, but they also apparently can spawn at the build limit height AND in structures where mob spawns are disabled completely!

**Comment by deftesthawk** [comment]
I've been getting this issue too, as a work around I used the "Mob Filter" mod and put this inside the config file.

```
rules:

 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:atolla_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:barrel_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:blue_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:cauliflower_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:compass_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:fried_egg_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:lions_mane_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:moon_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:nomura_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']

```
