### ISSUE TITLE
Jellyfish spawning in dry caves and stuff

### ISSUE THREAD

**Issue by steve-the-player** [hybridlabs/hybrid-aquatic#7]
From what I can gather, the jellyfish are spawning by checking for biome and light level. However, even if it's a river/ocean biome on the surface, it might be bone-dry underground in the caves. I think that adding the check for whether or not there is water before spawning (like squid do) should fix this issue, and probably also the one where people have dealt with flying jellyfish (https://github.com/hybridlabs/hybrid-aquatic/issues/3). Not something I've personally encountered, but similar.

**Comment by pewblaze** [comment]
Hi ive got the same issue with ne newest version. Is there a way to fix that? 
![2024-02-06_14 15 36](https://github.com/hybridlabs/hybrid-aquatic/assets/96242065/b2277a7f-9ecc-404d-b21d-0016cc70c353)

**Comment by MysticKoko** [comment]
Hey, sorry for the late reply - was busy with university.
This should be fixed in the latest version (1.2.2), and more edits to jellyfish spawning and behaviour are being worked on for the coming update as well, including a fix to the jumping jellyfish bug.

**Comment by weegeeluigi** [comment]
I'm on 1.2.2 and they still spawn in caves and fall from the ceiling.  Thought I had a bug with slime but I noticed some that were still alive walking around.

**Comment by MysticKoko** [comment]
> I'm on 1.2.2 and they still spawn in caves and fall from the ceiling. Thought I had a bug with slime but I noticed some that were still alive walking around.

Hmm, I didnt run into the issue while testing, but we'll take another look at it and hopefully finally fix it in the coming update(s) since we're making changes to jellyfish anyway

**Comment by deftesthawk** [comment]
I've been getting this issue too, as a work around I used the "Mob Filter" mod and put this inside the config file.

```
rules:

 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:atolla_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:barrel_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:blue_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:cauliflower_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:compass_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:fried_egg_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:lions_mane_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:moon_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:nomura_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']

```
